### PR TITLE
Add The Man's Masterpiece

### PR DESCRIPTION
**Pull request by EafAtta**

### CODE REVIEW

**Review by rjkiv — CHANGES_REQUESTED** [review]
-pro bass:
the riff at measure 10 and others like it: you can move the A0 down to E5 for simplicity's sake
measures 118-119: the timing is off for a few notes, seems like a copying error
further reduce EM

-pro guitar: further reduce EM
-the riff from measures 21-23 and others like it is wrong

**Comment by EafAtta** [comment]
> -pro bass: the riff at measure 10 and others like it: you can move the A0 down to E5 for simplicity's sake measures 118-119: the timing is off for a few notes, seems like a copying error further reduce EM
> 
> -pro guitar: further reduce EM -the riff from measures 21-23 and others like it is wrong

Alright added the suggestions! And yeah that riff was on the wrong strings lol

**Review by rjkiv — CHANGES_REQUESTED** [review]
you need to further reduce E and M - for example, measure 120 on pro guitar still has a full power chord despite that not being allowed for these difficulties, and there need to be fewer notes in each measure (see the pins in the discord for more guidelines)

**Comment by EafAtta** [comment]
Made another attempt at reducing EM

> you need to further reduce E and M - for example, measure 120 on pro guitar still has a full power chord despite that not being allowed for these difficulties, and there need to be fewer notes in each measure (see the pins in the discord for more guidelines)

Made another attempt at reducing EM

**Pull request merged**
