### PR TITLE
Added Schizophrenia

### PR DESCRIPTION
**Pull request by WarGod480**
this is, by far, my worst chart...
not proud of it one bit

### CODE REVIEW

**Comment by jdk13** [comment]
Pro Guitar: 

 - Measure 13 and 14, seems like a pitch from the muted guitar strum was taken as a 9th fret in the 4th beat, try putting that as a mute, applies to all other instances in this riff for consistency. Another 9th fret on the e (1 _e_ & a) of the 1st beat but doesn't seem to be anywhere else (I've seen so far)
 - Measure 15 and others, _technically_ you don't have to reduce the amount of notes in a hard chord (this im not 100% sure on someone else may have to verify this)
 - Measure 16-17,  you currently have is a 2 note chord riff with a main melody note supported by a 5th fret D string, but what I hear in the stem is the 5th fret on the B string. Applies to all future measures with the same riff
 - Measure 29-30, a higher C note seems to be present in both measures, this can fixed by tacking on another 5th fret G string to measure 29, and replacing the 7th fret G string to a 5th fret G string. This does _not_ apply to measure 55 and 56
 - Measure 31 and 57, replace the 8th fret B string note with a chord 033 chord starting from the G string going up.
 - Measure 33-34, your notes seem to be a whole octave down. I went ahead and adjusted it and will send you a pic of what it sound like (according to my best judgement with the stem) check carefully again in case I missed anything. Applies to Measures 59 and 60
 - Measure 46, not sure if the length of the 4 is intentional or not but i'd leave that space empty to match with the 5 fret chart or add another mute in between. (also for consistency between these repeating riffs)
 - Measure 48, same thing with length, a mute on the e of 4, and a note on the 3 and then & of the 3rd beat.
 - Measures 72 and 76, the last two notes also have their root ascending by a half step.
 - Measure 81-84, could be arpeggiated
 - Measure 86, I hear an extra high C# somewhere but I can't exactly pinpoint which notes in the measure it's being played.
 - Measure 107, 0220 (i think)
 - Measure 109, 5777, and i'm not quite sure what the note after that is but the 86 isn't right (the first 6 is though)
 
 double check what you're hearing from both of the two guitar channels in the mogg since there are some parts where one channel is clearer than the other 
 
 Pro Bass
 Looks good but weird thought about
 - Measure 77, the pitch seems to audibly drop from the measure before, but it kinda fits the way it is written but I can't see a better way to chart it since it is a whole synth.

**Comment by carlmylo** [comment]
Stuff from measure 5 to measure 7 could be optimized. Check image for reference. The arpeggio is just to make it all look united. The next chord could probably be optimized as well.
image
Chord at measure 29 might be better to have as X0221X because of the following chord. Speaking of...
Chord at Measure 30 might be better as XX0212. Saying this because listen to 30.3 to 30.4. You can hear the C creeping in, which would make it a D7 chord.

**Comment by WarGod480** [comment]
@jdk13 
> * Measure 15 and others, _technically_ you don't have to reduce the amount of notes in a hard chord (this im not 100% sure on someone else may have to verify this)

it just sounds to me that the chord has the extra E note, ill keep it for now


> * Measure 16-17,  you currently have is a 2 note chord riff with a main melody note supported by a 5th fret D string, but what I hear in the stem is the 5th fret on the B string. Applies to all future measures with the same riff

i dont quite understand what you mean here 


> * Measure 48, same thing with length, a mute on the e of 4, and a note on the 3 and then & of the 3rd beat.

tweaked, needs new inspection


> Pro Bass Looks good but weird thought about
> * Measure 77, the pitch seems to audibly drop from the measure before, but it kinda fits the way it is written but I can't see a better way to chart it since it is a whole synth.

should i change it to an Open E as oposed to what it is now?

**Comment by jdk13** [comment]
Pro Guitar:

- Measure 5 & 7can be a single arpeggio, erase the 3 ghost notes in the second chord and turn the arpeggio marker into one long one. Same for Measure 37 and 39, 94 and 96
- Measure 28 seems to have those 5 fret B strings I wanted but you misplaced them in the Hopo marker
- Measure 30 & 31 you have a stray 114 note with the velocity of 81... I dont know if that's what was in the 5 fret chart or you accidently misclicked
- Measure 31 tack an extra open B note to this High G (3rd fret on E) like this 
image
maybe even mark it as a G chord
- Measure 71 and 72 I didn't hear before but add an extra 5 and 7 on top of the chords of every note (keep it at 7 for the 8-7-6 to make it 7-8-7-6) applies to 75 and 76
- Measure 73 add an extra 8 fret B string to the chords to make it 7-9-9-8. Does not apply to measure 69.

Pro Bass

I don't even know what you changed but it sounds perfect now (unless you didn't touch it and I'm just imagining things)
The only thing I really have to say is raise the the difficulty by a bit (maximum of a value of like 80-90 tbh) currently you have it rated lower than Just the Way You Are by Bruno Mars, that bass part is just 3 notes repeating (3, 0 and 1 on the 2nd string) and this is def more than that so you can raise it but still keep it within 0 dot.

Other than that it looks good, gonna need to have Carl to look over it one more time again just in case cause I'm not too confident myself that i got everything.

**Comment by WarGod480** [comment]
https://youtu.be/KJ86lXPpR84

**Review by rjkiv — CHANGES_REQUESTED** [review]
fix sustain gaps during parts like 0:41
3:29: change chord root note from G to C

once these are fixed, I can merge

**Pull request merged**
