### PR TITLE
Uncontrollable Urge Keys Upgrade

### PR DESCRIPTION
**Pull request by BowlsforRick**
There's a A Major chord being played throughout most of the backing stem, I couldn't make out whether it was a synth or a guitar but I decided to chart it. It makes the song less empty and more enjoyable to play imo

### CODE REVIEW

**Comment by BowlsforRick** [comment]
Video Preview: https://youtu.be/WpRtFOv7IKs

**Comment by exoticri** [comment]
overall looks good, only thing that needs to be changed is making the last sustain in the intro on easy match how it is on medium

**Comment by exoticri** [comment]
sorry scratch that, match it to how this pattern is charted at the end of chorus 2a

**Comment by BowlsforRick** [comment]
Fixed

**Comment by exoticri** [comment]
lgtm

**Pull request merged**
