### PR TITLE
Add Fell In Love With A Girl

### PR DESCRIPTION
**Pull request by trishiskukky**
Guitar: E Standard (as we all know and luv it)

### CODE REVIEW

**Comment by WarGod480** [comment]
- Measure 16: The chord seem off. There's a B chord in the midi when the audio is playing an F#
- Measure 21: Similar situation. Midi is playing a D chord whilst the audio is playing an A
- These issues are repeated throughout the song, as it's basically a loop
- **Reminder: Don't forget to also do this for the HME reductions**

**Review by rjkiv — CHANGES_REQUESTED** [review]
-fix your F root notes - they should be marked as F#
-when playing E chords, why do you have one particular chord play on 4 strings while the rest are 3? maybe either make them all 3 strings or 4 strings for consistency's sake

**Comment by trishiskukky** [comment]
1. how do i change the root note
2. i did the 4 note thing cuz the 5 fret chart had a different chord there for some reason
3. anyways ill get to it

**Comment by trishiskukky** [comment]
oops i meant how do it do an f#

**Pull request merged**
