### PR TITLE
added holiday

### PR DESCRIPTION
**Pull request by CaptnCH**

### CODE REVIEW

**Comment by SCOTT0852** [comment]
Just checking but like, this is a WIP, right? You're not actually planning to submit a broken chart with no difficulty reductions and trainers that crash the game, right?

**Comment by CaptnCH** [comment]
i honestly forgot about those but everything else is fine

**Comment by SCOTT0852** [comment]
"everything else is fine" dude, it literally crashes the game if you attempt to use a basic vanilla rb3 feature

**Review by rjkiv — CHANGES_REQUESTED** [review]
You need to add trainers and actual reductions. Also remove all the text markers for the chord names and assign them to the corresponding midi notes

**Comment by CaptnCH** [comment]
alright well i'll work on that

**Pull request closed without merging**
