### PR TITLE
tragickingdom added

### PR DESCRIPTION
**Pull request by Aloquendiar**
tragickingdom added
(don't speak about the update of Don't Speak)

### CODE REVIEW

**Review by rjkiv — CHANGES_REQUESTED** [review]
-pro bass: chart according to the audio, I spotted several instances (such as measure 38) where the chart doesn't match the audio
-pro guitar: do the reductions, fix your chord root notes
-both: fix your trainers so they start and end at a clean number of measures, especially if you're setting them to loop - also make sure your trainer markers are correct (I saw in pro guitar, you have a loop trainer 9 in between start/end trainer 4)

**Review by rjkiv — CHANGES_REQUESTED** [review]
pro bass: fix measures 70, 74, and the BRE leadup and final note - the pitches are wrong
pro guitar: measures 16-19, add slides to make smoother transitions, and add mutes where appropriate to make smoother transitions between chords or significant fret position changes
also, the same trainer issue I brought up in the last change request was not addressed

**Comment by Aloquendiar** [comment]
Regarding what you told me in the previous request, I know that harmnoix officially made trainers with 8 measures and I think that dividing into two trainers of 4 measures is not good

**Review by rjkiv — CHANGES_REQUESTED** [review]
pro bass: measures 225 - end of BRE, fix pitches

**Review by rjkiv — CHANGES_REQUESTED** [review]
the notes for the chart themselves seem good now, now you need to fix the chord names
run through the chart in-game and you'll see what i mean

**Review by rjkiv — CHANGES_REQUESTED** [review]
-fix remaining incorrect chord names
-also in the tuning table, move the entry so that No Doubt is alphabetical

**Pull request merged**
