### PR TITLE
added Its My Life

### PR DESCRIPTION
**Pull request by Aloquendiar**
Well, it seemed strange to me that this RB3 DLC doesn't have the update. (sorry hugh for the another pr)

### CODE REVIEW

**Comment by Aloquendiar** [comment]
I forgot the preview again:
https://www.youtube.com/watch?v=g2ESD_9YuoQ

**Comment by jdk13** [comment]
Pro Bass:
Measure 21 and 29 beat 4& - A String Fret 1 instead of Fret 3 (It's a B flat)
Measure 23, 31, 56 beat 4& - E String fret 3 instead of A string Fret 3 (It's a G)
Measure 55 beat 3& - D String Fret 1 instead of A string
Measure 107 - starting beat on beat 3 it should go  E4 E4 A1 A3
Hard Reductions can likely be reduced further to 4 quarter notes in the chorus

Pro Guitar:

Starting at measure 78 in the solo to measure 80, some of the C notes do not line up with the 5 fret chart and stem. Try switching your grid to triplet for that area to line them up. Applies to reductions
You _could_ reduce the hard solo more to just quarter notes as well but it would results in just one of the two alternating notes for the entirety fo the solo. Might need extra input on this.
 
 Easy and medium are good, trainers are good, dta is good, bass transposition is also good (unless there was a different way to do it)

**Review by rjkiv — CHANGES_REQUESTED** [review]
- fix spelling in table entry
- pro bass: redo the chart, you have it as E standard but the lowest note played sounds like a C, meaning this would actually be C standard or D Drop C - make sure you're charting to the audio as well

**Review by rjkiv — CHANGES_REQUESTED** [review]
pro bass - double check your octaves, for example, on measures 3 and 5, those C's should be one octave lower

**Review by rjkiv — CHANGES_REQUESTED** [review]
pro bass 77-81 - should be an octave lower
also if we're gonna be pedantic, the tuning table entry should be "It's"

**Pull request merged**
