### PR TITLE
Added Use It

### PR DESCRIPTION
**Pull request by WarGod480**

### CODE REVIEW

**Review by rjkiv — CHANGES_REQUESTED** [review]
- add the guitar tuning info alphabetically in the table rather than appended to the end
- run your upgrade through magma, i'm seeing things like pro bass measure 68, where a note's fret is lower than the current left hand position, or on pro bass measure 80, despite having notes on the 9th fret, the left hand position is set to 2nd fret
- i would also suggest moving the notes on pro bass measure 40 down from D2 down to A7 for easier transitioning to G9, since i don't hear a slide in the audio
- and if you do the above, rework your chart around that
- for pro guitar, when transitioning between chords, instead of one singular muted note in between chords, use full muted chords - otherwise in gameplay you'd be strumming one note in between chords rather than all the strings, which would feel awkward

**Comment by WarGod480** [comment]
If I rework the pro bass, would it be okay if i rework everything leading up to measure 41, is it's the only part of the chart where i did an awkward 2-9 fretting?
(P.S. Magma flagged measure 68, as you mentioned, but not 80 :/ both will be fixed by the next PR)

**Comment by rjkiv** [comment]
> If I rework the pro bass, would it be okay if i rework everything leading up to measure 41, is it's the only part of the chart where i did an awkward 2-9 fretting? (P.S. Magma flagged measure 68, as you mentioned, but not 80 :/ both will be fixed by the next PR)

If there's no other 2-9 transition, I think that should work

**Comment by WarGod480** [comment]
Updated the .mid file and also placed the guitar tuning in the right place

**Review by rjkiv — CHANGES_REQUESTED** [review]
-you need the song_id in the upgrades.dta, if you don't include it the game crashes

**Pull request merged**
