### PR TITLE
Add Pork and Beans Pro Strings

### PR DESCRIPTION
**Pull request by kevinturner**
All difficulties and trainer sections authored and tested against a separately compiled song via Onyx. This is my first time authoring for this kind of upgrade, so this needs some quick checks on some parts:

- ID matches and upgrades existing songs correctly. I assume I'm supposed to use the ID from the original song's DTA file.
- Trainers work as intended once upgraded. For whatever reason, I can't get trainers to appear in-game when songs are compiled as separate packages via Onyx, even when they come from otherwise working files.
- I used tiers originally when setting difficulty, not really sure how ranks work. Gave it my best guess for a Tier 1 on Guitar and Tier 2 on Bass.
- I have this set to in-game Eb Standard. It seems like it works the way it should, barring some slightly weird chord names on Hard and Medium due to me removing the extended bass note on the chords.

### CODE REVIEW

**Comment by rjkiv** [comment]
Thank you for your contribution, love seeing more people get into pro!

Pro guitar looks good, pro bass needs some more work.

- Yes, you're supposed to use the ID from the original song's dta file.
- These are presented on the repo as standalone upgrades, so the trainers should work natively. If you need a CON built, I believe there's a tutorial on it on this repo.
- Rock Band handles difficulty tiering differently than say, something like Clone Hero - instead of being a hard 0-6, there's a difficulty threshold mapping that the game uses. Do you have a Discord? If so, I recommend joining the [Milohax Discord server](https://discord.gg/xrba4CjdNC) - myself and some other pro charters can give you that mapping, and other useful tools/advice for pro charting in general.
- The real tuning is Eb Standard yes, but in-game, you have to treat it like it's E Standard. HMX did this in order to keep the labels for chord shapes consistent (for example, if you're playing a song with a capo, although the actual sound a G chord shape makes, for example, will be different, the shape is still G).
- Overall, great start so far!

**Review by rjkiv — CHANGES_REQUESTED** [review]
see above

**Comment by kevinturner** [comment]
Still couldn't ever get a proper upgrade to recognize on my PS3, but I was able to test the rest of the changes with a separate Onyx build and it still looks and plays like I would expect it to.

**Comment by kevinturner** [comment]
Chord text events are removed, I'm not sure the autogenerated ones are necessarily better. I moved up all of the roots a half-step to match E Standard tuning.

**Comment by rjkiv** [comment]
We're getting there!

I loaded the chart in-game, and in practice, for RB3, I think we should mute pro bass note A4 on measures 19 and 51 (so the result is a muted note, sliding into A9).

Also, slash chords aren't showing up in the chord names with the current chord note implementation. I suspect it might be because of the several autogenned "hide chord names" notes - remove those please.

Finally, for the upgrades.dta, set the upgrade_version to 1 - turns out, setting it to anything else will not have the upgrade playable in-game. Also, since you mentioned wanting 1-dot and 2-dot for the instrument difficulties, change the difficulty values to whatever threshold you feel is right based off the mapping that was provided.

Thank you for your continued response to feedback!

**Pull request merged**
