### PR TITLE
Afterlife Keys Upgrade

### PR DESCRIPTION
**Pull request by BowlsforRick**

### CODE REVIEW

**Review by rjkiv — CHANGES_REQUESTED** [review]
add glissando markers to the fast parts on measures 7 and 107

**Comment by BowlsforRick** [comment]
Added glissando markers as requested

**Review by rjkiv — CHANGES_REQUESTED** [review]
fix/adjust your key shift/range markers - in-game, around the bridge, I saw the keys shift outside of the green G key while it was still playing

**Comment by exoticri** [comment]
lgtm

**Pull request merged**
