### PR TITLE
Added The Scientist

### PR DESCRIPTION
**Pull request by jdk13**

### CODE REVIEW

**Review by rjkiv — CHANGES_REQUESTED** [review]
- you don't need left hand markers for every single note, instead you can apply one and then only apply more when you sense that your hand will have to move up/down
- pro guitar: you can move the A chord seen on measure 41 (and subsequent A chords) up to the middle 4 strings for easier transitioning
- ditto with the A# chord on measure 61
- ditto with the last 3 chords in the song
- reductions look good, just fix the above

**Comment by jdk13** [comment]
Hugh.

**Comment by jdk13** [comment]
This is the one. (also git wasn't liking the readme in alphabetical so i put it at the end could that be changed after the merge)

**Review by rjkiv — CHANGES_REQUESTED** [review]
- you need to change the chords toward the end for the reductions so they match expert
- fix the left hand positions too

**Pull request merged**
